# Generated by Django 4.2.1 on 2023-06-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuerySetAPI', '0003_student_gread_student_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gread',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='join',
            field=models.DateTimeField(),
        ),
    ]
