# Generated by Django 4.2.1 on 2023-06-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuerySetAPI', '0004_alter_student_gread_alter_teacher_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='pass_date',
            field=models.DateField(),
        ),
    ]
